name: "Collaboration Cycle"
description: "Core ticket for products and features going through the Collaboration Cycle."
title: "Collaboration Cycle for [Team Name, Product Name, Feature Name]"
labels: ["collab-cycle-review", "collaboration-cycle", "governance-team"]
assignees:
  - briandeconinck 
body:
  - type: markdown
    attributes:
      value: "## VFS product information"
  - type: input
    id: product-team
    attributes:
      label: VFS team name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product name
    validations:
      required: true
  - type: input
    id: feature-name
    attributes:
      label: Feature name
      description: If applicable
    validations:
      required: false
  - type: input
    id: product-label
    attributes:
      label: GitHub label for product
      description: Enter a label from the va.gov-team repo
    validations:
      required: true
  - type: input
    id: feature-label
    attributes:
      label: GitHub label for feature
      description: If applicable
    validations:
      required: true
  - type: input
    id: start-date
    attributes:
      label: Start date of enhancement
    validations:
      required: true
  - type: input
    id: feature-launch-date
    attributes:
      label: Feature launch date
    validations:
      required: false
  - type: input
    id: 508-request
    attributes:
      label: VA 508 Office audit request ticket number
    validations:
      required: false
  - type: input
    id: production-url
    attributes:
      label: Production URL
    validations:
      required: true
  - type: textarea
    id: front-end-information
    attributes:
      label: Other front-end information
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Kickoff questions"
  - type: markdown
    attributes:
      value: |
        Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.
  - type: dropdown
    id: visible-changes
    attributes:
      label: Will your work result in visible changes to the user experience?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: user-research
    attributes:
      label: Are you doing research with VA.gov users?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: changes-to
    attributes:
      label: Will your work involve changes to...
      description: For tools and applications, take into account if any static page entry points will need updates.
      options:
        - Tools and applications
        - Static pages
        - Both
    validations:
      required: true
  - type: dropdown
    id: analytics-domo
    attributes:
      label: Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: other-analytics
    attributes:
      label: If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: dropdown
    id: business-owner
    attributes:
      label: Who is the VA business owner for this product?
      options:
        - VHA (Veterans Health Administration)
        - VBA (Veterans Benefits Administration)
        - NCA (National Cemetery Administration)
        - VACO (Veterans Affairs Central Office)
        - Other
    validations:
      required: true

  - type: input
    id: other-business-owner
    attributes:
      label: (If Other) Please specify the VA business owner
    validations:
      required: false
