name: "Collaboration Cycle"
description: "Core ticket for products and features going through the Collaboration Cycle."
title: "Collaboration Cycle for [Team Name, Product Name, Feature Name]"
labels: ["collab-cycle-review", "collaboration-cycle", "governance-team"]
assignees:
  - briandeconinck 
body:
  - type: dropdown
    id: visible-changes
    attributes:
      label: Will your work result in visible changes to the user experience?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: user-research
    attributes:
      label: Are you doing research with VA.gov users?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: checkboxes
    id: changes-to
    description: For tools and applications, take into account if any static page entry points will need updates.
    attributes:
      label: "Will your work involve changes to: (select all that apply)"
      options:
        - label: Tools and applications
        - label: Static pages
    validations:
      required: true
  - type: dropdown
    id: analytics-domo
    attributes:
      label: Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: other-analytics
    attributes:
      label: If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: dropdown
    id: business-owner
    attributes:
      label: Who is the VA business owner for this product?
      options:
        - VHA (Veterans Health Administration)
        - VBA (Veterans Benefits Administration)
        - NCA (National Cemetery Administration)
        - VACO (Veterans Affairs Central Office)
        - Other
    validations:
      required: true

  - type: input
    id: other-business-owner
    attributes:
      label: (If Other) Please specify the VA business owner
    validations:
      required: false
