name: "Collaboration Cycle Requests"
description: "Begin engaging with the Collaboration Cycle."
title: "Collaboration Cycle for [Team Name, Product Name, Feature Name]"
labels: ["collab-cycle-review", "collaboration-cycle", "governance-team"]
assignees:
  - briandeconinck 
body:
  - type: markdown
    attributes:
      value: "# Collaboration Cycle"
  - type: markdown
    attributes:
      value: |
        The [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) is where teams who are building products on VA.gov get feedback and guidance on their product to ensure it meets VA.gov experience standard. Teams engage with the Collaboration Cycle throughout their product’s lifecycle.
  - type: markdown
    attributes:
      value: |
        Before engaging with the Collaboration Cycle, please review the questions below to help Platform determine what level of support and which touchpoints are needed for your work. (Learn more about the [Collaboration Cycle kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html).)
  - type: markdown
    attributes:
      value: |
        **Fields marked with an asterisk (*) are required.**
  - type: markdown
    attributes:
      value: "## VFS product information"
  - type: markdown
    attributes:
      value: |
        Note: Some product information may not be available at this time. Please answer as many questions as possible as completely as possible.
  - type: input
    id: product-team
    attributes:
      label: VFS team name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product name
    validations:
      required: true
  - type: input
    id: feature-name
    attributes:
      label: Feature name
      description: If applicable
    validations:
      required: false
  - type: input
    id: product-label
    attributes:
      label: GitHub label for product
      description: Enter a label from the va.gov-team repo
    validations:
      required: true
  - type: input
    id: feature-label
    attributes:
      label: GitHub label for feature
      description: If applicable
    validations:
      required: false
  - type: input
    id: start-date
    attributes:
      label: Start date of enhancement
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Kickoff questions"
  - type: markdown
    attributes:
      value: |
        Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.
  - type: dropdown
    id: visible-changes
    attributes:
      label: Will your work result in visible changes to the user experience?
      options:
        - "Yes"
        - "No"
        - "Other/Unsure (please explain in the comments after submission)"
    validations:
      required: true
  - type: dropdown
    id: user-research
    attributes:
      label: Are you doing research with VA.gov users?
      options:
        - "Yes"
        - "No"
        - "Other/Unsure (please explain in the comments after submission)"
    validations:
      required: true
  - type: dropdown
    id: changes-to
    attributes:
      label: Will your work involve changes to...
      description: For tools and applications, take into account if any static page entry points will need updates.
      options:
        - "Tools and applications"
        - "Static pages"
        - "Both"
        - "Other/Unsure (please explain in the comments after submission)"
    validations:
      required: true
  - type: dropdown
    id: analytics-domo
    attributes:
      label: Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
      options:
        - "Yes"
        - "No"
        - "Other/Unsure (please explain in the comments after submission)"
    validations:
      required: true
  - type: dropdown
    id: other-analytics
    attributes:
      label: If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?
      options:
        - "Yes"
        - "No"
        - "Other/Unsure (please explain in the comments after submission)"
    validations:
      required: false
  - type: dropdown
    id: business-owner
    attributes:
      label: Who is the VA business owner for this product?
      options:
        - "VHA (Veterans Health Administration)"
        - "VBA (Veterans Benefits Administration)"
        - "NCA (National Cemetery Administration)"
        - "VACO (Veterans Affairs Central Office)"
        - "Other/Unsure (please explain in the comments after submission)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Artifacts"
  - type: input
    id: product-outline
    attributes:
      label: Product outline
      description: Please enter a URL for your product outline. See the [product outline template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md).
    validations:
      required: true
